Refactor test
GiuseppeCorrao/Flow_Open pull request #10
Opened 2022-08-30 15:22 UTC by samueleCatalano

ho sistemato il test

2022-08-31 15:14 UTC, aegroto requested changes

2022-08-31 15:14 UTC, aegroto commented on src/businesslogic/BusinessLogic.java
> +    void calculatePassive() {
aggiungi visibilità ai metodi

2022-09-01 08:34 UTC, GiuseppeCorrao requested changes

2022-09-01 08:34 UTC, GiuseppeCorrao commented on test/BusinessLogicTest.java
> +        Assertions.assertEquals(73.26, BusinessLogic.calculateIva(333));
il test si calcola su un prodotto, inizializzane uno

2022-09-02 08:31 UTC, francoforte123 commented on src/businesslogic/BusinessLogic.java
> +    void calculatePassive() {
è giusto

2022-09-02 10:28 UTC, closed without merging