Cart class
GiuseppeCorrao/Flow_Open pull request #16
Opened 2022-09-06 11:13 UTC by samueleCatalano

aggiunta la classe cart con annessi test e modificato la classe product. date un'occhiata.

2022-09-06 12:25 UTC, francoforte123 commented
secondo me, potrebbe andare...

2022-09-07 08:19 UTC, francoforte123 commented
per me va bene

2022-09-08 12:35 UTC, GiuseppeCorrao requested changes

2022-09-08 12:35 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +        this.productsOnCart = productsOnCart;
di nuovo non hai cambiato questa parte del codice 
public Cart(){
this.productOnCart = new ArrayList<Product>();

2022-09-08 12:35 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +        return p.getQuantity();
questo metodo non elimina tutti gli elementi dalla lista, dovrebbe fare questo invece ritorna solo un intero

2022-09-08 12:35 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +        productsOnCart.add(p);
metti che sia void non serve un booleano

2022-09-08 12:35 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +        double sum = p.getPrice() + p1.getPrice();
la somma la devi fare all'interno di un ciclo for cosi fai la somma solo di 2 oggetti ma nella lista c'è ne vanno di più

2022-09-08 12:35 UTC, GiuseppeCorrao commented on test/CartTest.java
> +        Assertions.assertEquals(product.getQuantity(), cart.buy(product));
non stai testando correttamente il metodo, pensa alla logica che sta dietro

2022-09-08 12:35 UTC, GiuseppeCorrao commented on test/CartTest.java
> +        Assertions.assertTrue(cart.addedOnCart(computer));
devi fare una comparazione booleana all interno dell assertion prima richiama il metodo fuori dall assertion poi lo verifichi

2022-09-08 12:46 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +        p.setQuantity(-1);
toglie la quantità all'interno della lista, ciclando con un ciclo for

2022-09-14 09:51 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +    public boolean buy(Product p) {
in questo metodo non devi passare un prodotto ogni volta che vuoi comprare dal carrello

2022-09-14 09:51 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +        productsOnCart.add(p);
è ancora un booleano

2022-09-14 09:53 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +        double priceDelivery = 15;
non mi convince questo metodo, ritorna il prezzo o comunque il pricedelivery diventa il prezzo del prodotto e non va bene

2022-09-14 09:54 UTC, GiuseppeCorrao commented on test/CartTest.java
> +        cart.buy(computer);
è sbagliato ancora una volta prima devi chiamare l'add on cart poi richiami il metodo da testare e successivamente lo testi

2022-09-14 10:13 UTC, GiuseppeCorrao commented on test/CartTest.java
> +        Product smartphone = new Product(Brand.ACER, "SJDJDJJSD", "CKDSKSKKS", 300.00, "SKSKK", "smartphone", 10);
ok rivedilo

2022-09-14 10:23 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +        double priceDelivery = 15;
quindi, lavora con il total price e non con il prodotto, il prezzo della spedizione non deve essere uguale al prezzo del prodotto

2022-09-16 14:32 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +    public void abort() {
conviene usare clear anche qui

2022-09-16 14:33 UTC, GiuseppeCorrao commented on src/products/Product.java
>                  ", product='" + product + '\'' +
rimuovi il to string

2022-09-16 14:33 UTC, GiuseppeCorrao commented on test/CartTest.java
> -        String input = "y";
ripulisci il codice commentato

2022-09-20 08:40 UTC, merged