feat: obtained user from database
GiuseppeCorrao/Flow_Open pull request #30
Opened 2022-09-29 15:32 UTC by samueleCatalano

ho fatto il task per ottenere gli oggetti di user dal database, ditemi se va bene

2022-09-30 15:06 UTC, GiuseppeCorrao commented on SQL_command/CreateTable.sql
> +PRIMARY KEY (product_id));
perchè hai aggiunto una parentesi ?

2022-09-30 15:14 UTC, GiuseppeCorrao commented on test/UserTest.java
> +
non stai testando a dovere il metodo, dovè la chiamata al metodo, si che non devi testare la connessione ma devi verificare se effettivamente ci siano quegli utenti all'interno della lista prendendoli appunto dal db.

2022-09-30 15:15 UTC, GiuseppeCorrao commented on test/UserTest.java
> +        List<User> list = new ArrayList<>();
stessa cosa del metodo precedente

2022-09-30 15:16 UTC, GiuseppeCorrao requested changes
Richiesta di cambiamento in seguito alla revisione del codice

2022-10-02 19:02 UTC, samueleCatalano commented
ho pushato un altro commit per mostrarvi il mio fix, ma il codice è ancora da aggiornare quindi se va bene ditemelo così lo aggiorno e si mergia

2022-10-03 12:51 UTC, GiuseppeCorrao commented on src/entities/User.java
> +                userObject.add(new User(nameUser, surnameUser, age, birthday, sex, email, password));
mi sembra buono

2022-10-03 12:52 UTC, GiuseppeCorrao commented on test/UserTest.java
> +
no così non stai testando bene il metodo, deve prendere dal db, quindi devi inserire degli utenti nel DB

2022-10-03 13:35 UTC, GiuseppeCorrao commented on SQL_command/CreateTable.sql
> +PRIMARY KEY (product_id));
togli la parentesi

2022-10-03 13:37 UTC, GiuseppeCorrao commented on SQL_command/CreateTable.sql
> -    );
riformatta questo codice sql ci sono errori come parentesi doppie

2022-10-04 12:58 UTC, closed without merging