fix: downgrade of the project to the state of the main
GiuseppeCorrao/Flow_Open pull request #39
Opened 2022-10-04 15:44 UTC by samueleCatalano

ho riportato lo stato del progetto a quello del main, spostato calculateIva() da BusinessLogic a Cart e concatenato totalPrice(), priceDelivery() e calculateIva()

2022-10-06 15:24 UTC, GiuseppeCorrao commented on src/products/Cart.java
>              sum += productsOnCart.get(i).getPrice();
in questo modo fai la somma per la lunghezza non va bene

2022-10-06 15:27 UTC, GiuseppeCorrao commented on test/CartTest.java
>          Assertions.assertEquals(15, cart.priceDelivery());
il metodo sempre fuori dalla verifica devi metterlo

2022-10-07 11:14 UTC, GiuseppeCorrao commented on src/businesslogic/BusinessLogic.java
>      @Deprecated
reinserisci il metodo calculateIva

2022-10-08 13:04 UTC, francoforte123 commented
per me va bene

2022-10-08 13:22 UTC, GiuseppeCorrao commented on src/products/Cart.java
>              sum += productsOnCart.get(i).getPrice();
adesso mi sembra buono il metodo

2022-10-08 13:23 UTC, GiuseppeCorrao commented on src/products/Cart.java
> +        Cart cart = new Cart();
questo a cosa ti serve ?

2022-10-08 13:24 UTC, GiuseppeCorrao commented on src/products/Product.java
> +        return "Product{" + "brand=" + brand + ", color='" + color + '\'' + ", price=" + price + ", description='" + description + '\'' + ", name='" + name + '\'' + ", quantity=" + quantity + '}';
è ancora disordinato

2022-10-08 13:24 UTC, GiuseppeCorrao commented on src/products/Product.java
> +        return "Product{" + "brand=" + brand + ", color='" + color + '\'' + ", price=" + price + ", description='" + description + '\'' + ", name='" + name + '\'' + ", quantity=" + quantity + '}';
fai in modo che stampi ogni variabile per ogni riga con relativo valore e togli le parentesi

2022-10-08 13:25 UTC, GiuseppeCorrao commented on test/BusinessLogicTest.java
> +    void calculateDiscountTest() {
aggiungi qualche riga di spazio

2022-10-08 13:26 UTC, GiuseppeCorrao commented on test/BusinessLogicTest.java
> +        BusinessLogic businessLogic = new BusinessLogic();
a cosa ti serve questa istanza ?

2022-10-08 13:27 UTC, GiuseppeCorrao commented on test/CartTest.java
>      void buyTest() {
dovè il metodo buy aggiungi solo al carrello

2022-10-08 13:27 UTC, GiuseppeCorrao commented on test/CartTest.java
> +        Product product = new Product(Brand.ACER, "TravelMate P2", 329.00, "pc", "This PC works", 4, 8);
stessa cosa dovè la chiamata al metodo

2022-10-08 13:32 UTC, samueleCatalano commented on test/CartTest.java
> +        Product product = new Product(Brand.ACER, "TravelMate P2", 329.00, "pc", "This PC works", 4, 8);
il metodo l'ho richiamato, non so perché non ti spunta ma sul codice c'è

2022-10-08 13:32 UTC, GiuseppeCorrao commented on test/CartTest.java
> +        Product mouse = new Product(Brand.LG, "SJDJDJJSD", 3.0, "mouse", "SKSKK", 34, 30);
questo oggetto ha un costo di spedizione superiore a 30 testa bene il metodo

2022-10-08 13:32 UTC, samueleCatalano commented on test/CartTest.java
>      void buyTest() {
anche qui l'ho richiamato

2022-10-08 13:33 UTC, GiuseppeCorrao requested changes
risolvi le problematiche

2022-10-10 09:30 UTC, GiuseppeCorrao commented on test/BusinessLogicTest.java
> +    void calculateDiscountTest() {
sistemalo

2022-10-10 09:40 UTC, merged