Input login method with SQL
GiuseppeCorrao/Flow_Open pull request #42
Opened 2022-10-07 18:25 UTC by Waze27

2022-10-08 00:34 UTC, samueleCatalano commented
per me va bene

2022-10-08 13:07 UTC, francoforte123 commented
per me potrebbe andare

2022-10-08 13:17 UTC, GiuseppeCorrao commented on src/entities/LoginLogic.java
> +        return false;
in questo modo la variabile booleana non sarà sempre false ?, false lo potrebbe restituire all'interno del catch

2022-10-08 13:18 UTC, GiuseppeCorrao commented on src/entities/LoginLogic.java
> +        boolean logged;
a cosa serve questa variabile

2022-10-08 13:19 UTC, GiuseppeCorrao commented on src/entities/LoginLogic.java
> +    public boolean login(User userAccess) {
non capisco questo metodo, so che lo hai preso da internet ma mi sembra sbagliato. Dovrebbe comparare le variabili email e password del db con quelle che gli passiamo

2022-10-08 13:20 UTC, GiuseppeCorrao requested changes
non capisco bene come funzioni la logica, se potresti mettere del javadoc per far capire in che modo funzionano i metodi e se sono concatenati tra loro (mi è sembrato di no), nei metodi cerca di usare variabili con un nome meno generico Useraccess è per l'accesso ? poco intuitivo, inoltre il login dovrebbe prendere un utente in database confrontarlo con uno nel backend e se le credenziali matchano potrebbe ritorna true, ora non ho ben capito se lo hai fatto o no.

2022-10-10 09:43 UTC, GiuseppeCorrao commented
rimuovi la cartella .idea e pusha nuovamente, non avresti dovuto poterla pushare dato che in gitignore è un file ignorato

2022-10-10 12:49 UTC, merged